# Generated by Django 5.1.11 on 2025-09-07 13:33

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_create_model_Category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shop.models.path_to_category_image,
                        verbose_name="Путь до изображения",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="Описание для изображения не добавлено",
                        max_length=255,
                        verbose_name="Описание изображения",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
