# Generated by Django 5.1.11 on 2025-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_create_model_Tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название акции"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Скидка (%)"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="promotions",
                        to="shop.product",
                        verbose_name="Товары",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
    ]
