# Generated by Django 5.1.11 on 2025-09-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_update_some_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="products",
        ),
        # Ручное корректирование для удаления таблицы
        # (получилось что не специально, но выполнил требование по "обратной" миграции из ТЗ)
        migrations.RunSQL(
            "DROP TABLE IF EXISTS shop_promotion_products;",
            reverse_sql=(
                "CREATE TABLE shop_promotion_products"
                " (promotion_id bigint NOT NULL, product_id bigint NOT NULL);"
            ),
        ),
    ]
