# Generated by Django 5.1.11 on 2025-09-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_drop_M2M_autogen_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('limit', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Лимит продаж по акции')),
                ('quantity_sold', models.SmallIntegerField(default=0, verbose_name='Всего продано по акции')),
                ('price_with_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена в акции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Товар в акции',
                'verbose_name_plural': 'Товары в акции',
                'unique_together': {('promotion', 'product')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', through='shop.PromotionProduct', to='shop.product', verbose_name='Товары'),
        ),
    ]
