# Generated by Django 5.2.6 on 2025-09-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_create_M2M_between_Products_and_Promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='promotionproduct',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='shop.promotion', verbose_name='Акция'),
        ),
    ]
